version: "2"
services:
  goof-mongo:
    container_name: goof-mongo
    image: mongo:3
    ports:
      - "27017:27017"
  good-mysql:
    container_name: goof-mysql
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acme
    ports:
      - "3306:3306"
